require('./batchTest');
require('./chunksTest');
require('./encodingDecodingTest');
require('./filterTest');
require('./fixedSizeTest');
require('./linesTest');
require('./mapTest');
require('./rangeTest');
require('./seriesTest');
